# Generated by Django 4.0.2 on 2022-03-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('standard', models.CharField(max_length=64)),
                ('stream', models.CharField(max_length=64)),
                ('telephone', models.CharField(max_length=64)),
                ('email_address', models.CharField(max_length=64)),
                ('father_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obtainer', to='reports.students')),
            ],
        ),
    ]
