# Generated by Django 4.0.2 on 2022-03-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='first',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='physics',
        ),
    ]
