# Generated by Django 4.0.2 on 2022-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_first_students_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='physics',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
