# Generated by Django 4.0.2 on 2022-03-10 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.subjects'),
        ),
    ]
