# Generated by Django 4.0.2 on 2022-03-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_first_name_students_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='physics',
            field=models.FloatField(),
        ),
    ]
