# Generated by Django 4.0.2 on 2022-03-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_score_biology_remove_score_maths_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='student_id',
            new_name='student_name',
        ),
    ]
