# Generated by Django 4.0.2 on 2022-03-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_rename_student_id_score_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
