# Generated by Django 4.0.2 on 2022-03-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_student_roll_number_alter_student_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
    ]
