# Generated by Django 4.0.2 on 2022-03-07 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0006_students_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='last',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='students',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
