# Generated by Django 4.0.2 on 2022-03-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
