# Generated by Django 4.0.2 on 2022-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_students_first_name_remove_students_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='physics',
            new_name='Physics',
        ),
        migrations.AddField(
            model_name='reports',
            name='Maths',
            field=models.FloatField(default=0),
        ),
    ]
