# Generated by Django 4.0.2 on 2022-03-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_rename_physics_reports_physics_reports_maths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='Maths',
        ),
    ]
